server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/ordersdb}
    username: ${DB_USER:otellab}
    password: ${DB_PASS:otellab}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318}/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
